### ISSUE TITLE
Collaboration-friendly storage format

### ISSUE THREAD

**Issue by bgolinvaux** [mayank1513/vscode-extension-trello-kanban-board#35]
# Request 1

**Is your feature request related to a problem? Please describe.**
My feature is not related to a bug, but rather an inconvenience : you store the whole board as a single-line JSON file named `.tkb` (at least for the workspace version, I haven't tested the global one) which makes it a pain to merge when working collaboratively.

Formatting it as a proper JSON file would go a long way towards making merges easier.

Apologies if I missed something.

**Describe the solution you'd like**
Having a properly formatted JSON file, where as many newlines as required are used (even though multi-line text will necessarily be stored as a single line if in a single JSON string). Maybe an array of lines could be used to store card contents, so that it's even more merge-friendly.

**Describe alternatives you've considered**
Other [TODO.md](https://github.com/todomd/todo.md) based extensions are much more Git-friendly, but are certainly less extensible.

**Additional context**
N/A

# Request 2 (related)
Maybe allowing to open `TODO.md` files could be a nice idea?  This is straying away from your vision though.

# Request 3 
Nitpick : there's a small typo in your vscode extension page 

"🤩 _Don't forget to start this repo!_" should be "🤩 _Don't forget to **star** this repo!_"  😀

**Comment by mayank1513** [comment]
Hi,

thanks for contributing by reporting the issue in detail.

Though I was a little busy, I have updated the extension to create properly formatted JSON. Will fix the typo too. Thanks!

Will consider TODO.md as well. Feel free to start the discussion around the topic in the discussions tab.

**Comment by mayank1513** [comment]
Hope this helps.

**Comment by bgolinvaux** [comment]
Thank you very much !  I will test this asap.
