### ISSUE TITLE
Ability to style (e.g. colour) the kanban cards and columns

### ISSUE THREAD

**Issue by RoCrow** [mayank1513/vscode-extension-trello-kanban-board#39]
**Is your feature request related to a problem? Please describe.**

Not a problem, more a design limitation.

**Describe the solution you'd like**

Ideally, an options menu to colour:

- individual columns
- individual cards
    - manually, and
    - by tags in the card (first tag in the card will be the priority

Failing that, ability to do it via CSS

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/mayank1513) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/mayank1513/vscode-extension-trello-kanban-board/issues/39">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/mayank1513/vscode-extension-trello-kanban-board/issues/39/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/mayank1513/vscode-extension-trello-kanban-board/issues/39/pledge.svg">
</picture>
</a>

**Comment by west4me** [comment]
You can currently edit the CSS used for the board...
C:\Users\xxxxxxx\.vscode\extensions\mayank1513.trello-kanban-task-board-0.5.2\assets\index.css.

I found it helpful to visit the online version of the board to be able to see what classes are used where. They translate fairly well from browser to desktop.

**Comment by mayank1513** [comment]
I have added support for inline HTML in tasks as well.
