### ISSUE TITLE
Board issue when adding a link and clicking on it

### ISSUE THREAD

**Issue by OscarArroyoVega** [mayank1513/vscode-extension-trello-kanban-board#40]
**when adding a link in format [link_name](link_adress)**
After clicking the link, the task block goes to blank and it's a kind of triky to go back and recover the text in it.
 

**To Reproduce**

1. Add a link in format [link_name](link_adress)
2. Click on 'link_name'
3. the link is working correcly and being opened in the browser
4. the block where the link is goes to blank

**Expected behavior**
the block where the link is remains as it is, maybe the link changes color to "visited"

**Desktop (please complete the following information):**

- OS and framework: vscode 1.90.01 runing  in windows 11
- Browser: Chrome

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/mayank1513) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/mayank1513/vscode-extension-trello-kanban-board/issues/40">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/mayank1513/vscode-extension-trello-kanban-board/issues/40/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/mayank1513/vscode-extension-trello-kanban-board/issues/40/pledge.svg">
</picture>
</a>

**Comment by west4me** [comment]
There seems to be a function that closes tasks like an accordion. It happens randomly to me, doesn't seem to be only related to links. If shift is held when clicking on a task, it always collapses.
