### ISSUE TITLE
Allow for linebreaks/carriage return in tasks

### ISSUE THREAD

**Issue by west4me** [mayank1513/vscode-extension-trello-kanban-board#41]
Allow for linebreaks/carriage return in task. When the user pushes Enter or Shift+Enter, new lines are inserted. 
This feature would offer another way to format the task text.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/mayank1513) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/mayank1513/vscode-extension-trello-kanban-board/issues/41">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/mayank1513/vscode-extension-trello-kanban-board/issues/41/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/mayank1513/vscode-extension-trello-kanban-board/issues/41/pledge.svg">
</picture>
</a>

**Comment by west4me** [comment]
I updated this morning and I'm still not able to put a line break in between a paragraphs. They are removed when leaving focus on the task.

**Comment by mayank1513** [comment]
Markdown will remove extra newlines.

I believe this is how markdown and html etc. are parsed.

**Comment by mayank1513** [comment]
I have updated the extension. Now you should be able to use `html` code. Just use <br /> for extra line breaks. If having multiple line breaks is what the community supports largely, I will have that handled. But for now, let us stick with the popular markdown parsing and support your use case with html.

Thanks.

**Comment by west4me** [comment]
That exactly what I needed. Thanks!
