### ISSUE TITLE
The "_" seems to not be recognized in end of links 

### ISSUE THREAD

**Issue by Rozevskis** [mayank1513/vscode-extension-trello-kanban-board#47]
![image](https://github.com/mayank1513/vscode-extension-trello-kanban-board/assets/44755996/a36c2940-f279-486f-ba81-98676280add5)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/mayank1513) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/mayank1513/vscode-extension-trello-kanban-board/issues/47">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/mayank1513/vscode-extension-trello-kanban-board/issues/47/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/mayank1513/vscode-extension-trello-kanban-board/issues/47/pledge.svg">
</picture>
</a>

**Comment by mayank1513** [comment]
Please use Markdown syntax - [Your Link](https://link-with_)
